# Generated by Django 5.1.5 on 2025-01-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(blank=True, help_text='Укажите поставщика', null=True, related_name='products', to='electronic_trade.supplier', verbose_name='Поставщик'),
        ),
    ]
