# Generated by Django 5.1.5 on 2025-01-15 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_trade', '0005_alter_contact_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='supplier',
            field=models.OneToOneField(help_text='Укажите поставщика', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='electronic_trade.supplier', verbose_name='Поставщик'),
        ),
    ]
